Minor improvements

diff --git a/pkg-src/generic/ks-syncthing/usr/bin/syncthing-config-watcher b/pkg-src/generic/ks-syncthing/usr/bin/syncthing-config-watcher
--- a/pkg-src/generic/ks-syncthing/usr/bin/syncthing-config-watcher
+++ b/pkg-src/generic/ks-syncthing/usr/bin/syncthing-config-watcher
@@ -44,6 +44,11 @@ ST_SVC="syncthing@$PRIMARY_USER.service"
 if [ -e "$ST_CONFIG" ] && [ ! -L "$ST_CONFIG" ]; then
     >&2 echo "Config exists and is not a symlink. Storing config and replacing with symlink"
 
+    if ! [ -f "$SYSST_CONFIG" ]; then
+        >&2 echo "Target config file $SYSST_CONFIG doesn't exist! Can't continue."
+        exit 4
+    fi
+
     REACTIVATE="false"
     if systemctl is-active "$ST_SVC" &>/dev/null; then
         systemctl stop "$ST_SVC"
